//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.20 at 10:17:21 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/BAR")
package com.example.users.model;
